sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt -r org/repo GH_TOKEN=XXX-https://github.com/settings/tokens-XXX
  - secure: "mmCO91ji9Cb4lyt88Spezzl9KDhniOYnqMn7TjLHGhETAQ4aOa3B9Rf9YaBNKS0tj6KBuDKyau1Ld/wGQHrFIN9QA0XRW1qofHycA4giuJhYhA6fVZGhyqblpd1Kd+N1t3XeV2bZzQf62ViqoHx+QGed8GFaRDi/MD7gFGVhfXidCgzA+XnPXHvCR3YLJvn/agKPMU8BNNyb/RRT/NmEwcFsrkJjJTq+osq5bBG/2Wsz6Brg9dL9k7tTI/i9SGcdjDF69BoMGHzdyWTVlLHxe1ZsL30Fm8slSZPvV2omXAbaHzMlp5Aun0pPLrJKf1bOddBA5m4VCz+MvR4SLqi+XBe56iypMxBm3tHbGoxgMibDddQTW2oI98cIXpW0hNdUz7cn/3z2TY+QYzYICDx8uNzrJnVHrCOHPpRvWTcd5yfJOiFbOWME2qsN9VMKiNlSRC8cKqz0DWpUDwyAwxGChM0ghIrpHkondd68Opcj+kfZ6cYivMKywnnfAy1uudoe/YuWkTxVFtg0ws5VcDblDOtI76f2KysDEetlUKrkM6ik3ng16Dzs1yMPGGwvfQmI7LjYRQbQ8vtPfOs8cL+d+x4hLxy1LTp02wO7ujEy3cpgMcKtpRnaeXlJ8DGy1Z7QA8Ahm022UagylazeWSAHr2rt1FPsEsuzGnuO1+wu/7k="
  # Ex. travis encrypt -r org/repo SONATYPE_USERNAME=your_sonatype_account
  - secure: "igpX3ABlbhGzT5juScj/KxVtLLV+w0+HUTCM2MeYisQFZfnAEuHjdQ8Q7sRaQBnbsYCXurRwdN7IQDdVhBKCmDHQ152GQRShlz08CK8qNSCm+ZAkYV3lOkb6GuO+mrA7+F/18Yj08r4Ea7PAfs5dN3D363gVV/WQLqoK1PjHd1Pg6Rca+XOJH7x9U4HzDyczPP3jajcBACBAEGV8G+CSNoXswnQo4vhNVbvHXElF5xC6b+MgzqB6L2/W3+kqEQr7O+KNKXbdfczDSfKAUE6T2gLo2PlYV13kWRAyhGrhTZhPYBqBaqusj9ynirfyws1jKlnKZv9RupGeih7iVDu0DEmAXwz1ZIvx0idm6H1cnpuvW+zVC+uwSvetLcLdri/TADMygCyovROb6HXlrqhNZv6AI/D9VtkqTbv26DJsUiV+iMVh79g5fnigkRGKNaVwlnWHvcgWpp/z64ZalVIStEslWPxg8iiY1oXnEO/ZYq1Pz0BAUzZk6+U4xBhTZ2OP+VN4dPbZgLcLLJrf6jT56QHUw1PvdFg1+gsSfnw8Kqf+EboeZjpU6y6r5j2fjeYrH5HFTBd4zBv6chQ6vdsS820Xbz747MY0gUK6KR0NsloZTRZqrr/CC26PyWLK0ledGVRSZdpAtSCvnQLgL7M3TFvBfYNj8AQ8aQ3UtW0gTgk="
  # Ex. travis encrypt -r org/repo SONATYPE_PASSWORD=your_sonatype_password
  - secure: "XjmXh4PwiezA+XNpcyQUOB8a3TWmE5okoBzwaoQYcB8MVg0RFkya34HuoNCaINuhKOxVBJDRKgYhfUi/6lnNKNAgJxcxodxfV+ETXMxGNbDzgmYDwNSlpMATOjbRE3FEs00+KbI6OlTNxaOPBxdN6fV1SPKrZ2MvHSDfJDWTktSC1vE8VcKBpgB1tkNQxDnCA7fl1XxfOTvfJBCLURXsMXDkMDas6HrrYj0ou87BimWMHTC6TAMiEvxsv0J0KG9tuzAGYL0VAF7iPcWmuzV3yW0yMEJINO3T1l9ghulIwSsr3jYApVJl8w+1gw0cC0rW7/ZLtTHrn9ekwKlRliaInetR9PlCLPeKaDRpre6dLCUadcOR6hwFOKqNLOaTfp+PD85l40Fp5rLwTnmrmjPusiQ5YPoM2BUdF9jfjvNgo1Zr+dvG4zVTWxyLA+fiful+KcCxPG1kYxeX6AgVCXOvMgOFukppqsVTaIVrMLRZ7d7SnyriIDzy+1QRyJRC2vzoJH6Nc7hAov+UxMMvdfP3cP5zEMsM2pMiDRvTV3VAppbZ/v56xRJt9V1hyBJwmEByv7JTsDE5oM4NAF3X8F5u/JoR2eETVvkv+qjvelDKahbHPlc+a2ndrMWrr3E5ZeZs6PNsIdoFanPGn9gTuSNG3/jJ3YZWc/NVc2qd3Kra2PU="
  # Ex. travis encrypt -r org/repo BINTRAY_USER=your_github_account
  - secure: "O9CRUyXklPLwrhEkzrs/qf6FZevvJDxKFOLkGg+NGh5rk11lIsefROVFVkB1hWD/YDtior2PJqjwjdAUFm5RsXT8LCPRSA8FHkE6no1RJPgVnhYvDdgu/CuDE+v4DI/FCszRnV6nt5TFgTZCUbF/Q0gR/mWTU4d722qR/5oHVaQumnv0V/GiSvThCT4YaZFatk2WGhh6Lj0shi00blc1e7bzaPykBRZ3PAIXq4fIyIpcIHUUA42JL5vVHFl4Yun+CcHLboDs3+5/K9aXnX8OMSWS4i0P3Fijhx8Aok1NkK6IkospBLRnqHMd97o99P3FXVAKa775L8yqFKlcF5YZkb87w/vYLBwqsnj2QuQHSEWXKv6O0OWjDBkA2WMpWfEkOkSh+yDqskyacctEVobkRCQ6JWoCvEuUMaqck0Hdzf6xZ6KnIxzpsJ23L7O1MLbvR7BhjRD0W8pUbuW0BcSkPbV6ee24q8wsVvXHsH/cFau+XlcdmXKdiajrifVD3RyTT0T59cTU9HHSoRpSOty4+M8MebJ78Lg9kHaFW+x2085P3PrDUdXFZjuz7L28u0YO8EXIxX8WfWXa4XilBdo8G/ZmQ3kt4MorgTfyMIbxsQmLhR2CJR5XOxaJ2CkCbRRozWcEB6OvDHst7NVvrvzpsnDlx7mOvXEtS1lNDzWTKds="
  # Ex. travis encrypt -r org/repo BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx
  - secure: "UoN2MbXr62pth4JzydpCG0zO3Gn1/dtvZv2Paal2brkbdaotSyNca7itmeVpTdetd3qAuOyrNE9Yd7QG8+u1Z9harVdic43EtCbZjrTa3ZWTjQ/rMwgMNYPW254aaVhX9I9Vkf7/rgUlHo+UNjKuEZRejgpOYFpv3Kiynn8EfXXaJRNEF3dklIqIgqn4xqZNjTnwvK/3LKEs0XEuxk2/WJnz+HCIv3YRP3/3s0pnZ3vRaZUccP8Vd/UL3y8vs4riPOpUXHRSU2LwpSIKAwY5qEjmcQ/xQXVCbfstXQVJUXUhddiCkjZXda+dKr1UcU1EBKNtRVKMD5uku39IPST5NlQCO8OUmNwSTyntmumQYfkEUk21rV3Mxh+2zAGyE9/PSRjSz0K9Ya0ZV6rvY2Ht3PfQ12K2+dOTlUqA11crEX7h4MdlD/RLd/wXmPyogEEAtr8JdCDX/idurIZO2MLNvv85Y9tQeiK9uOHLCFHPFPbEqg/CKrdP761nfSLbIK5w8HeXcuk1nJ/rayqwTRaVdUlBFlxnxcku4TXGGc4cxxoTuWA3r/EKzVYY1jtVn2clLDMbiXo7QWaSt6+2CZDIs6ilaEsUPVc1Cw+USdHGyhUKNPSNrstCNswPfK9MN8Jvh/I+K8FEPhi6ugaEdU23u9samZBrIRyp5wdTHZ22SQE="
